comment: false

codecov:
  notify:
    after_n_builds: 1
    wait_for_ci: false

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

github_checks:
  annotations: false
